# Docker Compose for Local Development
# PostgreSQL ONLY - Server and Client run locally via npm

version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: trivia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: trivia_user
      POSTGRES_PASSWORD: trivia_pass
      POSTGRES_DB: trivia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trivia_user -d trivia_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
